import { Geist, Geist_Mono, Josefin_Sans } from "next/font/google";
import { ProductProvider } from "./context/productcontext";
import { CartProvider } from "./context/cartcontext";
import { AuthProvider } from "./context/AuthContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${josefinSans.variable} antialiased`}
      >
        <AuthProvider>
        <ProductProvider>
          <CartProvider>
        {children}
          </CartProvider>
        </ProductProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
